baseURL: "qwenlm.github.io"
title: Qwen
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

ignoreErrors: ["error-remote-getjson"]

# googleAnalytics: UA-123-45

defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
  zh:
    languageName: 简体中文
    weight: 2
    params:
      date_format: "2006年1月2日"


minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Qwen
  description: "Qwen"
  keywords: ["multi-modal", "machine learning", "blog"]
  author: Qwen
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]

  # custom site variables
  date_format: "January 2, 2006"
  default_theme: light # dark, light
  disable_theme_toggle: true
  disable_special_first_post: false
  disable_scroll_to_top: false
  displayFullLangName: true

  # custom site and page variables
  show_share_buttons: true
  show_bread_crumbs: true
  hide_meta: false
  math: false
  
  # single page only
  show_code_copy_buttons: true
  show_word_count: true
  use_hugo_toc: true
  show_toc: false
  toc_open: false
  comments: false
  show_reading_time: true
  show_post_nav_links: false
  
  # list page only
  hide_summary: false
  show_rss_button_in_section_term_list: false

  assets:
    disable_hljs: true # to disable highlight.js
    disable_fingerprinting: false
    disable_scroll_bar_style: false

    favicon: "https://acd-assets.alicdn.com/acd_work/tongyi/assets/logo.svg"
    favicon16x16:  "https://acd-assets.alicdn.com/acd_work/tongyi/assets/logo.svg"
    favicon32x32:  https://acd-assets.alicdn.com/acd_work/tongyi/assets/logo.svg"
    apple_touch_icon:  "https://acd-assets.alicdn.com/acd_work/tongyi/assets/logo.svg"
    safari_pinned_tab:  "https://acd-assets.alicdn.com/acd_work/tongyi/assets/logo.svg"

  label:
    text: "OFA-Sys"
    # icon: /image/logo.svg
    icon_svg: '<svg width="25px" height="24px" viewBox="0 0 25 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <linearGradient x1="76.7202373%" y1="41.6070847%" x2="18.306123%" y2="65.5065085%" id="linearGradient-9_1k7ha4jv-1">
            <stop stop-color="#797BEB" offset="0%"></stop>
            <stop stop-color="#373080" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="Symbols" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="_编组-7" fill="url(#linearGradient-9_1k7ha4jv-1)">
            <path d="M12.2746711,0 C12.5125388,0 12.7434104,0.12583746 12.8693403,0.33556656 L14.2545696,2.71249636 L20.3971523,2.71249636 C20.63502,2.71249636 20.8658915,2.83833382 20.9918215,3.04806292 L22.7338523,6.02621614 C22.8597822,6.23594524 22.8597822,6.5016021 22.7338523,6.7113312 L22.6988718,6.76725896 C22.6708873,6.80920478 22.6359068,6.8511506 22.5939301,6.88610545 L21.2156969,9.24905331 L24.2659999,14.4922808 L24.3429571,14.6041363 C24.4339065,14.8138654 24.4548948,15.0795223 24.3919298,15.2682785 L22.7898212,18.0087387 C22.6638912,18.2184678 22.4400158,18.3443053 22.195152,18.3443053 L19.4176972,18.3582872 L16.353402,23.6504515 C16.227472,23.8601806 16.0035966,23.9860181 15.7587328,23.9860181 L12.2886633,24 L12.2396906,24 C12.0158151,23.9860181 11.7989358,23.8601806 11.6869981,23.6644334 L10.1968271,21.1127294 L4.13120166,21.1127294 C4.0822289,21.1267113 4.04025225,21.1267113 3.9912795,21.1267113 C3.75341183,21.1267113 3.52254028,21.0008739 3.39661034,20.7911448 L1.79450165,18.0506845 C1.66857171,17.8479464 1.66857171,17.5892805 1.79450165,17.3725604 L3.17273489,14.9816487 L0.0944474553,9.69647539 C-0.0314824851,9.49373726 -0.0314824851,9.23507137 0.0944474553,9.0183513 L1.80849387,6.02621614 C1.92043159,5.81648704 2.15130315,5.69064958 2.40316303,5.69064958 C2.466128,5.67666764 2.51510075,5.69064958 2.56407351,5.70463152 L5.40449327,5.70463152 L8.44080406,0.46140402 C8.45479628,0.4194582 8.46179238,0.38450335 8.48278071,0.35653947 L8.49677292,0.33556656 C8.62270286,0.12583746 8.84657831,0 9.09144209,0 L12.2816672,0 L12.2746711,0 Z M9.04246933,0.72706088 L5.74730256,6.41071949 L2.3751786,6.41071949 L8.93752771,17.6871541 L5.59338819,17.6871541 L3.97728728,20.4765511 L10.5606247,20.4765511 L12.2396906,23.3708127 L18.8020397,12.0664142 L20.4811056,14.9466939 L23.7203035,14.9327119 L20.4181406,9.24905331 L22.0832143,6.38275561 L9.00049268,6.39673755 L10.6795586,3.51645791 L9.04946544,0.72706088 L9.04246933,0.72706088 Z M16.1435187,9.82930382 L12.2187023,16.5755899 L8.2938858,9.82930382 L16.1435187,9.82930382 Z" id="_形状"></path>
        </g>
    </g>
</svg>'
#     icon_svg: '<svg 
#    width="41.687111mm"
#    height="37.703426mm"
#    viewBox="0 0 41.687111 37.703426"
#    version="1.1"
#    id="svg5"
#    xmlns:xlink="http://www.w3.org/1999/xlink"
#    xmlns="http://www.w3.org/2000/svg"
#    xmlns:svg="http://www.w3.org/2000/svg">
#   <defs
#      id="defs2">
#     <linearGradient
#        id="linearGradient3999">
#       <stop
#          style="stop-color:#0000ff;stop-opacity:0.67479676;"
#          offset="0.16"
#          id="stop3995" />
#       <stop
#          style="stop-color:#000000;stop-opacity:0;"
#          offset="1"
#          id="stop3997" />
#     </linearGradient>
#     <linearGradient
#        id="linearGradient3945">
#       <stop
#          style="stop-color:#00ff00;stop-opacity:0.67479676;"
#          offset="0.16"
#          id="stop3941" />
#       <stop
#          style="stop-color:#000000;stop-opacity:0;"
#          offset="1"
#          id="stop3943" />
#     </linearGradient>
#     <linearGradient
#        id="linearGradient3902">
#       <stop
#          style="stop-color:#ff0000;stop-opacity:0.67479676;"
#          offset="0.16"
#          id="stop3898" />
#       <stop
#          style="stop-color:#000000;stop-opacity:0;"
#          offset="1"
#          id="stop3900" />
#     </linearGradient>
#     <radialGradient
#        xlink:href="#linearGradient3902"
#        id="radialGradient3904"
#        cx="61.55265"
#        cy="90.307182"
#        fx="61.55265"
#        fy="90.307182"
#        r="21.788235"
#        gradientUnits="userSpaceOnUse"
#        gradientTransform="matrix(1.0083361,0,0,0.97200857,0.08213891,3.8855297)" />
#     <radialGradient
#        xlink:href="#linearGradient3945"
#        id="radialGradient3904-5"
#        cx="61.55265"
#        cy="90.307182"
#        fx="61.55265"
#        fy="90.307182"
#        r="21.788235"
#        gradientUnits="userSpaceOnUse"
#        gradientTransform="matrix(1,0,0,0.99427089,30.91008,20.549678)" />
#     <radialGradient
#        xlink:href="#linearGradient3999"
#        id="radialGradient3904-5-0"
#        cx="61.55265"
#        cy="90.307182"
#        fx="61.55265"
#        fy="90.307182"
#        r="21.788235"
#        gradientUnits="userSpaceOnUse"
#        gradientTransform="translate(1.2194985,37.034278)" />
#   </defs>
#   <g
#      id="layer1"
#      transform="translate(-52.088293,-91.487792)">
#     <path
#        id="path3871-7"
#        style="fill:url(#radialGradient3904-5);fill-opacity:1;stroke:none;stroke-width:1.59542;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:1"
#        d="m 83.472675,91.487792 a 20.988234,20.867992 0 0 0 -11.998234,18.851448 20.988234,20.867992 0 0 0 11.998234,18.85198 l 10.30273,-18.85198 z" />
#     <path
#        id="path3871-7-8"
#        style="fill:url(#radialGradient3904-5-0);fill-opacity:1;stroke:none;stroke-width:1.6;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:1"
#        d="m 62.772396,106.3532 a 20.988234,20.988234 0 0 0 -10.408667,2.76624 l -0.275436,0.50694 10.572999,19.45721 h 21.020939 a 20.988234,20.988234 0 0 0 0.07803,-1.74201 20.988234,20.988234 0 0 0 -20.987865,-20.98838 z" />
#     <path
#        id="path3871"
#        style="fill:url(#radialGradient3904);fill-opacity:1;stroke:none;stroke-width:1.58402;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:1"
#        d="M 62.489152,91.531243 52.256337,109.68384 a 21.163194,20.400744 0 0 0 9.891512,2.3819 21.163194,20.400744 0 0 0 21.163345,-20.400886 21.163194,20.400744 0 0 0 -0.0021,-0.133611 z" />
#     <circle
#        style="fill:none;stroke:#959595;stroke-width:1.6;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:0.735203"
#        id="path4787"
#        cx="71.982582"
#        cy="108.95269"
#        r="0.80230254" />
#   </g>
# </svg>'
    iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Posts
  #       url: posts
  #     - name: Tags
  #       url: tags

  # home-info mode
  # home_info_params:
  #   title: "OFA: Towards Unified AI Models"
  #   header:
  #     # background: "linear-gradient(36deg, var(--hero1) 0%, var(--hero2) 80%);"
  #     background_images: "/image/outpainting-home-right-optimized.jpg"
  #     gradient: false
  #   # content: Welcome to my blog

  # social_icons:
  #   # - name: twitter
  #   #   url: "https://twitter.com/"
  #   # - name: stackoverflow
  #   #   url: "https://stackoverflow.com"
  #   - name: github
  #     url: "https://github.com/OFA-Sys"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    link_full_images: true
    responsive_images: true
    hidden: false # hide everywhere but not in structured data
    hidden_in_list: false # hide on list pages and home
    hidden_in_single: false # hide on single page

  # edit_post:
  #   url: "https://github.com/<path_to_repo>/content"
  #   text: "Suggest Changes" # edit text
  #   append_file_path: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    findAllMatches: false
    minMatchCharLength: 2
    keys: ["title", "summary"]

    threshold: 0.1
    ignoreLocation: false
    location: 0
    distance: 1000
    
menu:
  main:
    - identifier: api
      name: Resources
      url: /resources
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20
    - identifier: publication
      name: Publication
      url: /publication
      weight: 30
    - identifier: about
      name: About
      url: /about
      weight: 40
    # - identifier: search
    #   name: SEARCH
    #   url: /search
    #   weight: 50
    # - identifier: categories
    #   name: CATEGORIES
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: TAGS
    #   url: /tags/
    #   weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      footnote: true
  highlight:
    style: vs
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
    home:
        - HTML
        - JSON # is necessarylog